# Generated by Django 2.2.1 on 2019-09-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_type',
        ),
    ]
